version: '3'

networks:
  server:
    external: true
    name: open-im-server_server

services:
  openim-chat:
#    image: ghcr.io/openimsdk/openim-chat:${CHAT_BRANCH}
    # image: registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-chat:${CHAT_BRANCH}
    # image: openim/openim-chat:${CHAT_BRANCH}
    build: .
    container_name: openim-chat
    healthcheck:
      test: ["CMD", "/openim/openim-chat/scripts/check_all.sh"]
      interval: 60s
      timeout: 10s
      retries: 5
    ports:
      - 10008:10008
      - 10009:10009
    volumes:
      - ./logs:/openim/openim-chat/logs
      - ./_output:/openim/openim-chat/_output
      - ./config:/openim/openim-chat/config
      - ./scripts:/openim/openim-chat/scripts
    restart: always
    user: root:root
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "2"
    networks:
      server:
        ipv4_address: 172.28.0.10